set shell=zsh
set number

" Keymaps
map <C-p> :NERDTreeToggle<CR>

call plug#begin()

" Language specific
Plug 'pearofducks/ansible-vim'
Plug 'sudar/vim-arduino-syntax'
Plug 'plasticboy/vim-markdown'
Plug 'scrooloose/syntastic'
Plug 'Glench/Vim-Jinja2-Syntax'
Plug 'fatih/vim-go'
Plug 'michaeljsmith/vim-indent-object'
Plug 'lervag/vimtex'
Plug 'xuhdev/vim-latex-live-preview'
" Colorscheme
Plug 'junegunn/seoul256.vim'
Plug 'altercation/vim-colors-solarized'
Plug 'chriskempson/base16'
Plug 'morhetz/gruvbox'
"Else
Plug 'junegunn/vim-easy-align'
Plug 'Valloric/YouCompleteMe'
Plug 'bling/vim-airline'
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'Xuyuanp/nerdtree-git-plugin', { 'on' : 'NERDTreeToggle'}
Plug 'jiangmiao/auto-pairs'
Plug 'chrisbra/Colorizer'
Plug 'junegunn/goyo.vim'
Plug 'amix/open_file_under_cursor.vim'
Plug 'KabbAmine/vCoolor.vim'
Plug 'tpope/vim-commentary'
Plug 'terryma/vim-expand-region'
Plug 'tpope/vim-fugitive'
Plug 'terryma/vim-multiple-cursors'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-sensible'

call plug#end()

colorscheme seoul256

nnoremap <F4> :NERDTreeToggle <cr>
